function lastPart_new = gen_lastPart_new(lastPart)
    % 定义映射关系
    old_names = ["female01", "female04", "female06", "female78", ...
                 "female41", "femaleVIVO", "female23", "female51", ...
                 "female25", "female69",...
                 "male92", "male97", "male48", "male59", "male39", ...
                 "maleVIVO", "male21", "male46", "male22", "male28", ...
                 "femalevivo","malevivo"];
    
    new_names = ["f01", "f02", "f03", "f04", ...
                 "f05", "f06", "f07", "f08", "f09", "f10",...
                 "m01", "m02", "m03", "m04", "m05", "m06", "m07", ...
                 "m08", "m09", "m10","f06","m06"];
    
    % 初始化 lastPart_new 为 lastPart
    lastPart_new = lastPart;
    
    % 遍历 old_names 和 new_names，逐个替换
    for i = 1:length(old_names)
        lastPart_new = strrep(lastPart_new, old_names(i), new_names(i));
    end
    

end