function [picname_groups] = gen_picname_groups(lastPart)
    % 拟合椭球并保存结果
    if strrep(lastPart,"Add","") == "inLab"
        picname_groups=["female1makeup","female1nomakeup",...
        "female2makeup","female2nomakeup",...
        "female3makeup","female3nomakeup",...
        "female4makeup","female4nomakeup",...
        "female5makeup","female5nomakeup",...
        "male1","male2","male3","male4"];
    elseif strrep(lastPart,"Add","") == "indoor"
        picname_groups=["indoor01","indoor02","indoor03","indoor04","indoor05",...
            "indoor06","indoor07","indoor08","indoor09","indoor10"];
    elseif strrep(lastPart,"Add","") == "night"
        picname_groups=["night01","night02","night03","night04","night05",...
            "night06","night07","night08","night09","night10"];
    elseif strrep(lastPart,"Add","") == "outdoor"
        picname_groups=["outdoor01","outdoor02","outdoor03","outdoor04","outdoor05",...
            "outdoor06","outdoor07","outdoor08","outdoor09","outdoor10"];
    elseif strrep(lastPart,"Add","") == "sunset"
        picname_groups=["sunset01","sunset02","sunset03","sunset04","sunset05",...
            "sunset06","sunset07","sunset08"];
    end
end