function T = summarize_for_excel_final(fit_table)
% Flatten arrays to Excel-friendly summaries; includes D_equation numeric
n = height(fit_table);
lab_n   = zeros(n,1);
lab_L   = zeros(n,1);
lab_a   = zeros(n,1);
lab_b   = zeros(n,1);
score_n = zeros(n,1);
score_min = zeros(n,1);
score_max = zeros(n,1);
par_len = zeros(n,1);
for i=1:n
    Lv = fit_table.lab_values{i};
    if ~isempty(Lv)
        lab_n(i) = size(Lv,1);
        lab_L(i) = mean(Lv(:,1));
        lab_a(i) = mean(Lv(:,2));
        lab_b(i) = mean(Lv(:,3));
    else
        lab_n(i)=0; lab_L(i)=NaN; lab_a(i)=NaN; lab_b(i)=NaN;
    end
    sc = fit_table.opinion_scores{i};
    if ~isempty(sc)
        score_n(i)   = numel(sc);
        score_min(i) = min(sc);
        score_max(i) = max(sc);
    else
        score_n(i)=0; score_min(i)=NaN; score_max(i)=NaN;
    end
    pv = fit_table.par{i};
    if ~isempty(pv)
        par_len(i) = numel(pv);
    else
        par_len(i) = 0;
    end
end
T = table( ...
    string(fit_table.source), ...
    lab_n, lab_L, lab_a, lab_b, ...
    score_n, score_min, score_max, ...
    par_len, ...
    string(fit_table.fit_equation), ...
    fit_table.lab_center, ...
    fit_table.average_lab, ...
    fit_table.cct, ...
    fit_table.illuminance, ...
    string(fit_table.scene), ...
    string(fit_table.lighting), ...
    fit_table.D_equation, ...
    string(fit_table.model_ethnicity), ...
    string(fit_table.model_id), ...
    string(fit_table.observer_type), ...
    string(fit_table.opinion_score_range), ...
    'VariableNames', { ...
        'source', ...
        'lab_count','lab_mean_L','lab_mean_a','lab_mean_b', ...
        'score_count','score_min','score_max', ...
        'par_length', ...
        'fit_equation', ...
        'lab_center', ...
        'average_lab', ...
        'CCT', ...
        'illuminance', ...
        'scene', ...
        'lighting', ...
        'D_equation', ...
        'model_ethnicity', ...
        'model_id', ...
        'observer_type', ...
        'opinion_score_range' ...
    } ...
);
end